### ISSUE TITLE
Replace no-color-hex rule with property-value whitelist

### ISSUE THREAD

**Issue by pearsonhenri** [palantir/stylelint-config-palantir#2]
We want to ban custom color declarations and use exclusively Blueprint colors rather than just hex-format color declarations. This rule: https://github.com/stylelint/stylelint/tree/master/src/rules/declaration-property-value-whitelist would be a good way to restrict the set of allowed color properties.

(Not sure about how this works given that this repo is open-source but Blueprint is not)

**Comment by giladgray** [comment]
i try to minimize my use of the black/whitelist properties because they require a lot of maintenance. might be easiest to rely on `"no-color-hex": true` and `"color-named": "never"` and         `"color-no-invalid-hex": true`.

**Comment by giladgray** [comment]
@pearsonhenri whitelisting the colors seems like a project-level decision and so the whitelist should live in your project's `stylelint.config.js`, rather than in this project.

there's also the fact that the Blueprint colors are not (yet) available to the wider internet community 😄
