### ISSUE TITLE
CSS property ordering inconsistent/arbitrary

### ISSUE THREAD

**Issue by lucasray** [palantir/stylelint-config-palantir#26]
Opening this issue as a place to discuss CSS property ordering.

Our property ordering is claimed to be loosely based on the "concentric css" model described here: https://rhodesmill.org/brandon/2011/concentric-css/. This model is based on css available in 2011, which was a much different place than where we stand today. The model roughly lays out css in a way that describes the box "from the outside in" (based on the comments noted on the linked page):
  1) how does this box interact with elements around it
  2) visibility of the box
  3) intrinsic height and width definitions outside of the box's content
  4) intrinsic height and width definitions of the content
  5) styles that affect internals of the box (like `color`)

This model is no longer semantically meaningful with new css patterns, like flex containers. There are a number of `flex` properties which affect different behaviors of an element. If we want to maintain the rough semantics of "outside in", for example, `flex` should be defined under `1)`, since it affects how this element interacts with its parent (how it grows, shrinks, and the effective intrinsic size), but `flex-direction` should be defined under `5)`, since it affects how its children are laid out (a style internal to this element). However, it's obviously not ideal to have `flex` and `flex-direction` be defined so far apart from one another while reading. Currently, we arbitrarily decide to group all `flex` properties at the start. Since we're already breaking the semantics defined by the concentric css model, it can be confusing knowing where to find a specific property or type of property.

Additionally, new css properties are constantly being added and supported. CSS grid level 2 is nearly supported, so our property-ordering will need to be updated to support subgrids soon as well. Lack of definition will place the property below all those defined, creating further confusion about where to find a property (you now have to know which properties are defined in our spec).

I propose standardizing on alphabetical ordering, since alphabetization is a property that will be resilient to future CSS spec levels. Modern css specs already largely group rules in a way that consistent with alphabetization (e.g. all flex related rules are prefixed with `flex`) -- it's only a few old rules that would be negatively affected (like `top`/`right`/`bottom`/`left`).

**Comment by adidahiya** [comment]
I agree that the ordering we have now is probably outdated, it hasn't evolved much at all since I first created it. I'm open to alphabetical ordering, or just disabling the rule altogether... curious to hear thoughts from others as well, cc @styu

**Comment by styu** [comment]
Also agree that the ordering today feels arbitrary. Personally prefer alphabetical ordering so that styles are ordered consistently across codebases, as long as that plays well with prefixed styles (e.g. would want -webkit prefixed styles to be grouped together with what its prefixing).

**Comment by lucasray** [comment]
I think vender prefixes would be added in part of the less/sass compile stage, so wouldn't need to be impacted by stylelint, no?

**Comment by lucasray** [comment]
I'm still in favor of just alphabetizing, but an alternative ordering could be to group properties according to which css module they're part of (like everything defined for [grid level 2](https://www.w3.org/TR/css-grid-2/) first, then [flex level 1](https://www.w3.org/TR/css-flexbox-1/), etc.), and maybe order modules by recency or something. However, this and the current impl require constant updates to our ordering file as modules become adopted, or new levels of modules get released. I also am not sure if there's an easy way to tell which module any particular property is defined under (maybe some page exists similar to [this](https://www.w3.org/TR/css-grid-2/#index-defined-elsewhere) but for all properties?)

**Comment by tomshen** [comment]
I agree that the ordering is arbitrary and hard to keep track of (it hasn't been clear to anyone I've spoken to that they need to reference the ordering in this repo). I think alphabetical sorting helps keep the styles sufficiently organized and reduces merge conflicts just as well, but is much easier to follow.

**Comment by thelastnode** [comment]
+1 on grouping by module! I think having flex properties go together is a big win for readability.

**Comment by adidahiya** [comment]
switched to alphabetical property ordering in [v5.0](https://github.com/palantir/stylelint-config-palantir/releases/tag/5.0.0). prefixed properties go next to the non-prefixed ones.
